version: '3.1'

services:
  nodejs:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: devops_tp_nodejs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=admin
      - DB_PASSWORD=azertyuiop01
      - DB_NAME=test
      - DB_HOST=devops_tp_postgres
    volumes:
      - ./src:/home/node/app
    ports:
    - 3000:3000
    depends_on:
      - postgres
    networks:
      - sub_network_db
      - sub_network_node
  postgres:
    image: postgres
    container_name: devops_tp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azertyuiop01
      PGDATA: /data/postgres
    volumes:
      - ./database:/data/postgres
    restart: unless-stopped
    networks:
      - sub_network_db

networks:
  sub_network_db:
  sub_network_node:
