version: '3.1'

services:
  nodejs:
    build:
      context: ../
      dockerfile: Docker/nodejs/Dockerfile.prod
    container_name: devops_tp_nodejs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=admin
      - DB_PASSWORD=azertyuiop01
      - DB_NAME=test
      - DB_HOST=devops_tp_postgres
    ports:
    - 3000:3000
    depends_on:
      - postgres
    networks:
      - sub_network_db
      - sub_network_node
  postgres:
    image: postgres
    container_name: devops_tp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azertyuiop01
      POSTGRES_DB: test
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - sub_network_db
  redis:
    image: redis
    container_name: devops_tp_redis
    networks:
      - sub_network_db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - HOSTNAME=devops_tp_nodejs:3000
    networks:
      - sub_network_node
    ports:
      - 8080:80

networks:
  sub_network_db:
  sub_network_node:
